<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackageId>AiAssertions.DeepSeek</PackageId>
        <Title>AiAssertions DeepSeek Provider</Title>
        <Description>This package provides the DeepSeek model for AiAssertions.</Description>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\AiAssertions.Core\AiAssertions.Core.csproj" />
    </ItemGroup>

</Project>
